import { BreathTechnique } from '../types';

export const BUILTIN_TECHNIQUES: BreathTechnique[] = [

  // ─── BEGINNER ──────────────────────────────────────────────

  {
    id: 'box',
    name: 'Box Breathing',
    description: 'Der Klassiker für Fokus und innere Ruhe. Von Navy SEALs in Stresssituationen genutzt.',
    effects: ['balancing', 'calming'],
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Halten', seconds: 4, direction: 'right' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
      { label: 'Halten', seconds: 4, direction: 'right' },
    ],
  },
  {
    id: 'diaphragmatic',
    name: 'Zwerchfellatmung',
    description: 'Die Basis aller Atemarbeit. Tiefes Bauchatmen beruhigt sofort und verbessert die Sauerstoffaufnahme.',
    effects: ['calming', 'lung_training'],
    phases: [
      { label: 'Einatmen (Bauch)', seconds: 4, direction: 'up' },
      { label: 'Ausatmen (Bauch)', seconds: 6, direction: 'down' },
    ],
  },
  {
    id: 'equal',
    name: 'Gleichmäßiges Atmen',
    description: 'Sama Vritti aus dem Yoga. Bringt Körper und Geist ins Gleichgewicht.',
    effects: ['balancing'],
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
    ],
  },
  {
    id: 'triangle',
    name: 'Dreiecks-Atmung',
    description: 'Sanfter Einstieg in Atemhalte-Techniken. Beruhigt ohne zu überfordern.',
    effects: ['calming'],
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Halten', seconds: 4, direction: 'right' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
    ],
  },
  {
    id: 'pursed_lip',
    name: 'Lippenbremsatmung',
    description: 'Stärkt die Atemwege und lindert Kurzatmigkeit. Aus der Lungen-Rehabilitation.',
    effects: ['lung_training'],
    phases: [
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen (langsam)', seconds: 4, direction: 'down' },
    ],
  },
  {
    id: 'physiological_sigh',
    name: 'Physiologischer Seufzer',
    description: 'Der wissenschaftlich schnellste Stress-Reset. Wirkt in unter einer Minute (Stanford 2023).',
    effects: ['calming'],
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Nachatmen', seconds: 2, direction: 'up' },
      { label: 'Lang ausatmen', seconds: 8, direction: 'down' },
    ],
  },
  {
    id: 'relax',
    name: 'Entspannung 1:2',
    description: 'Doppelt so lang ausatmen wie einatmen — der direkte Weg in den Ruhemodus.',
    effects: ['calming'],
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Ausatmen', seconds: 8, direction: 'down' },
    ],
  },
  {
    id: '478',
    name: '4-7-8 Atmung',
    description: 'Die Einschlaf-Technik nach Dr. Andrew Weil. Beruhigt das Nervensystem zuverlässig.',
    effects: ['calming'],
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Halten', seconds: 7, direction: 'right' },
      { label: 'Ausatmen', seconds: 8, direction: 'down' },
    ],
  },
  {
    id: 'koherent',
    name: 'Kohärentes Atmen',
    description: 'Optimiert die Herzratenvariabilität. Ideale tägliche Basis-Praxis nach James Nestor.',
    effects: ['balancing', 'calming'],
    phases: [
      { label: 'Einatmen', seconds: 5, direction: 'up' },
      { label: 'Ausatmen', seconds: 5, direction: 'down' },
    ],
  },
  {
    id: 'soma_basic',
    name: 'SOMA Basis',
    description: 'Sanfte Pranayama-Variante. Korrigiert Atemgewohnheiten und baut Resilienz auf.',
    effects: ['balancing'],
    phases: [
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Halten', seconds: 1, direction: 'right' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
      { label: 'Halten', seconds: 1, direction: 'right' },
    ],
  },
  {
    id: 'energize',
    name: 'Energie-Boost',
    description: 'Schneller Rhythmus für Wachheit und Konzentration. Der Espresso unter den Atemübungen.',
    effects: ['energizing'],
    phases: [
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
    ],
  },
  {
    id: 'buteyko',
    name: 'Buteyko Basis',
    description: 'Reduziertes Atmen erhöht die CO₂-Toleranz. Bewährt bei Asthma und Schlafproblemen.',
    effects: ['lung_training', 'calming'],
    phases: [
      { label: 'Einatmen', seconds: 3, direction: 'up' },
      { label: 'Halten', seconds: 3, direction: 'right' },
      { label: 'Ausatmen', seconds: 6, direction: 'down' },
      { label: 'Halten', seconds: 3, direction: 'right' },
    ],
  },

  // ─── FORTGESCHRITTEN ───────────────────────────────────────

  {
    id: 'pranayama_ratio',
    name: 'Pranayama 1:4:2',
    description: 'Das klassische Yoga-Verhältnis mit langer Atemhaltung. Tiefe Entspannung und Klarheit.',
    effects: ['calming', 'lung_training'],
    isAdvanced: true,
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Halten (Kumbhaka)', seconds: 16, direction: 'right' },
      { label: 'Ausatmen', seconds: 8, direction: 'down' },
    ],
  },
  {
    id: 'bhastrika',
    name: 'Bhastrika (Blasebalg)',
    description: 'Kraftvolle Pumpatmung mit Retention. Weckt den ganzen Körper auf.',
    effects: ['energizing', 'lung_training'],
    isAdvanced: true,
    phases: [
      { label: 'Einatmen (kräftig)', seconds: 2, direction: 'up' },
      { label: 'Ausatmen (kräftig)', seconds: 2, direction: 'down' },
      { label: 'Einatmen (kräftig)', seconds: 2, direction: 'up' },
      { label: 'Ausatmen (kräftig)', seconds: 2, direction: 'down' },
      { label: 'Einatmen (kräftig)', seconds: 2, direction: 'up' },
      { label: 'Ausatmen (kräftig)', seconds: 2, direction: 'down' },
      { label: 'Tief einatmen', seconds: 3, direction: 'up' },
      { label: 'Retention', seconds: 15, direction: 'right' },
    ],
    rounds: 3,
  },
  {
    id: 'nadi_shodhana',
    name: 'Nadi Shodhana',
    description: 'Die Wechselatmung aus dem Yoga. Balanciert beide Gehirnhälften und zentriert.',
    effects: ['balancing'],
    isAdvanced: true,
    phases: [
      { label: 'Einatmen links', seconds: 4, direction: 'up' },
      { label: 'Halten', seconds: 4, direction: 'right' },
      { label: 'Ausatmen rechts', seconds: 4, direction: 'down' },
      { label: 'Einatmen rechts', seconds: 4, direction: 'up' },
      { label: 'Halten', seconds: 4, direction: 'right' },
      { label: 'Ausatmen links', seconds: 4, direction: 'down' },
    ],
  },
  {
    id: 'sudarshan_kriya',
    name: 'Sudarshan Kriya',
    description: 'Rhythmuswechsel von langsam zu schnell. In Studien wirksam bei Stress und gedrückter Stimmung.',
    effects: ['balancing', 'energizing'],
    isAdvanced: true,
    phases: [
      { label: 'Langsam ein', seconds: 3, direction: 'up' },
      { label: 'Langsam aus', seconds: 3, direction: 'down' },
      { label: 'Langsam ein', seconds: 3, direction: 'up' },
      { label: 'Langsam aus', seconds: 3, direction: 'down' },
      { label: 'Mittel ein', seconds: 2, direction: 'up' },
      { label: 'Mittel aus', seconds: 2, direction: 'down' },
      { label: 'Mittel ein', seconds: 2, direction: 'up' },
      { label: 'Mittel aus', seconds: 2, direction: 'down' },
      { label: 'Schnell ein', seconds: 1, direction: 'up' },
      { label: 'Schnell aus', seconds: 1, direction: 'down' },
      { label: 'Schnell ein', seconds: 1, direction: 'up' },
      { label: 'Schnell aus', seconds: 1, direction: 'down' },
      { label: 'Schnell ein', seconds: 1, direction: 'up' },
      { label: 'Schnell aus', seconds: 1, direction: 'down' },
      { label: 'Halten', seconds: 10, direction: 'right' },
    ],
    rounds: 3,
  },
  {
    id: 'co2_tolerance',
    name: 'CO₂-Toleranztraining',
    description: 'Trainiert die Chemorezeptoren. Verbessert Ausdauer, Schlaf und Atemökonomie.',
    effects: ['lung_training'],
    isAdvanced: true,
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Anhalten', seconds: 30, direction: 'right' },
      { label: 'Ausatmen', seconds: 6, direction: 'down' },
      { label: 'Erholen', seconds: 10, direction: 'up' },
    ],
    rounds: 5,
  },
  {
    id: 'kapalabhati',
    name: 'Kapalabhati',
    description: 'Die Schädelleuchten-Atmung. Schnelle Pumpstöße reinigen und energetisieren.',
    effects: ['energizing', 'lung_training'],
    isAdvanced: true,
    phases: [
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Pumpe', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Pumpe', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Pumpe', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Pumpe', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Retention', seconds: 20, direction: 'right' },
    ],
    rounds: 3,
  },
  {
    id: 'breath_of_fire',
    name: 'Feueratmung',
    description: 'Kontinuierliche Pumpatmung aus dem Kundalini Yoga. Erzeugt Wärme und Präsenz.',
    effects: ['energizing'],
    isAdvanced: true,
    phases: [
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 1, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
    ],
  },

  // ─── PROFI ─────────────────────────────────────────────────

  {
    id: 'wim_hof',
    name: 'Wim Hof Methode',
    description: 'Intensive Zyklen mit langer Retention. Für Energie, Fokus und Kältetoleranz.',
    warning: '⚠️ NIEMALS im Wasser oder beim Fahren. Kann Ohnmacht verursachen. Nur im Liegen in sicherer Umgebung.',
    effects: ['energizing'],
    isProfi: true,
    phases: [
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 1, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Retention', seconds: 30, direction: 'right' },
    ],
    rounds: 3,
  },
  {
    id: 'tummo',
    name: 'Tummo (Inneres Feuer)',
    description: 'Tibetische Technik für Körperwärme und tiefe Meditation. Der Ursprung der Wim-Hof-Methode.',
    warning: '⚠️ Nur im Liegen in warmer, sicherer Umgebung. Kann Schwindel verursachen. Nicht bei Herzproblemen.',
    effects: ['energizing'],
    isProfi: true,
    phases: [
      { label: 'Tief einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Tief einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Tief einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Tief einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Tief einatmen', seconds: 3, direction: 'up' },
      { label: 'Volle Retention', seconds: 45, direction: 'right' },
      { label: 'Ausatmen', seconds: 4, direction: 'down' },
    ],
    rounds: 4,
  },
  {
    id: 'holotropic_simplified',
    name: 'Holotropes Atmen',
    description: 'Schnelles verbundenes Atmen nach Grof. Kann veränderte Bewusstseinszustände auslösen.',
    warning: '⚠️ Starke emotionale Reaktionen und Ohnmacht möglich. NUR mit Begleitperson. Nicht bei Herzproblemen, Epilepsie, Schwangerschaft oder psychischen Erkrankungen.',
    effects: ['energizing'],
    isProfi: true,
    phases: [
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
      { label: 'Einatmen', seconds: 2, direction: 'up' },
      { label: 'Ausatmen', seconds: 2, direction: 'down' },
    ],
    rounds: 5,
  },
  {
    id: 'pranayama_extended',
    name: 'Pranayama 1:8:4',
    description: 'Sehr lange Atemhaltung für erfahrene Praktizierende. Tiefste Stille.',
    warning: '⚠️ Nur nach monatelanger Erfahrung mit kürzeren Verhältnissen. Nicht bei Bluthochdruck oder Herzproblemen.',
    effects: ['calming', 'lung_training'],
    isProfi: true,
    phases: [
      { label: 'Einatmen', seconds: 4, direction: 'up' },
      { label: 'Halten (Kumbhaka)', seconds: 32, direction: 'right' },
      { label: 'Ausatmen', seconds: 16, direction: 'down' },
    ],
  },
  {
    id: 'rebirthing',
    name: 'Verbundenes Atmen',
    description: 'Kreisförmiges Atmen ohne Pausen nach Leonard Orr. Emotionale Tiefenarbeit.',
    warning: '⚠️ Kann intensive Emotionen und Kribbeln auslösen. Begleitperson empfohlen. Nicht bei psychischen Erkrankungen.',
    effects: ['balancing'],
    isProfi: true,
    phases: [
      { label: 'Einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen (sofort)', seconds: 3, direction: 'down' },
      { label: 'Einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen (sofort)', seconds: 3, direction: 'down' },
      { label: 'Einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen (sofort)', seconds: 3, direction: 'down' },
      { label: 'Einatmen', seconds: 3, direction: 'up' },
      { label: 'Ausatmen (sofort)', seconds: 3, direction: 'down' },
    ],
    rounds: 10,
  },
];
